### ISSUE TITLE
All events are 1 hour early

### ISSUE THREAD

**Issue by pauljohanneskraft** [kordianbruck/TumCalProxy#8] opened 2017-01-11 16:31 UTC
After importing the calendar all my events appeared one hour early, possibly some kind of timezone/daylight saving time issue

**Comment by kordianbruck** [comment] 2017-01-11 20:32
In which program are you importing it? What are the settings in timezone on your machine?

The only place the timestamp for starting is touched is during the dupe check here: https://github.com/kordianbruck/TumCalProxy/blob/master/index.php#L141
Other than that, the Datestamp is not modified.

**Comment by kordianbruck** [comment] 2017-01-11 20:40
For example one of my events that starts at 10 am, that is being processed correctly:
```
BEGIN:VEVENT
UID:885397051@tum.de
DTSTART;TZID=Z:20161110T090000
SEQUENCE:0
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;TZID=Z:20161110T110000
URL:https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950262091
LOCATION:Boltzmannstraße 3\, 85748 Garching bei München
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Boltzmannstraße 3, 85748 
 Garching bei München";X-APPLE-RADIUS=49;X-TITLE="00.13.009A, Seminarraum 
 (5613.EG.009A)":geo:48.2622985\;11.6697764
SUMMARY:Programmoptimierung 
DESCRIPTION:00.13.009A\, Seminarraum (5613.EG.009A)\nProgrammoptimierung (I
 N2053) VU\, Standardgruppe\nfix\; Abhaltung\; Vorlesung
DTSTAMP:20170111T202312Z
END:VEVENT
```

Getting an example would help as well.

**Comment by pauljohanneskraft** [comment] 2017-01-11 20:51
I use Calendar on macOS Sierra, timezone is automatically determined by my location, currently my System Settings show "Mitteleuropäische Normalzeit" in German

**Comment by kordianbruck** [comment] 2017-01-11 20:54
"Mitteleuropäische Normalzeit" is CET. Can you post 2-3 Events from your ical file? (Download it directly with your browser and open with a text editor)

**Comment by pauljohanneskraft** [comment] 2017-01-11 21:01
BEGIN:VEVENT
UID:...@tum.de
DTSTART;TZID=Z:20170111T120000
SEQUENCE:0
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;TZID=Z:20170111T130000
URL:https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950264149
LOCATION:Boltzmannstraße 15\, 85748 Garching bei München
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Boltzmannstraße 15, 85748
  Garching bei München";X-APPLE-RADIUS=49;X-TITLE="MW 0001, Gustav-Niemann
 -Hörsaal (5510.EG.001)":geo:48.26600380750642\;11.670241355022874
SUMMARY:G: BS 
DESCRIPTION:MW 0001\, Gustav-Niemann-Hörsaal (5510.EG.001)\nGrundlagen: Be
 triebssysteme und Systemsoftware (IN0009) VO\, Standardgruppe\nfix\; Abhal
 tung\;
DTSTAMP:20170111T102303Z
END:VEVENT

BEGIN:VEVENT
UID:...@tum.de
DTSTART;TZID=Z:20170112T073000
SEQUENCE:0
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;TZID=Z:20170112T090000
URL:https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950262669
LOCATION:Boltzmannstraße 15\, 85748 Garching bei München
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Boltzmannstraße 15, 85748
  Garching bei München";X-APPLE-RADIUS=49;X-TITLE="MW 0001, Gustav-Niemann
 -Hörsaal (5510.EG.001)":geo:48.26600380750642\;11.670241355022874
SUMMARY:Analysis 
DESCRIPTION:MW 0001\, Gustav-Niemann-Hörsaal (5510.EG.001)\nAnalysis für 
 Informatik [MA0902] VO\, Standardgruppe\nfix\; Abhaltung\;
DTSTAMP:20170111T102303Z
END:VEVENT

BEGIN:VEVENT
UID:...@tum.de
DTSTART;TZID=Z:20170116T124500
SEQUENCE:0
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;TZID=Z:20170116T141500
URL:https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950264149
LOCATION:Boltzmannstraße 15\, 85748 Garching bei München
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Boltzmannstraße 15, 85748
  Garching bei München";X-APPLE-RADIUS=49;X-TITLE="MW 0001, Gustav-Niemann
 -Hörsaal (5510.EG.001)":geo:48.26600380750642\;11.670241355022874
SUMMARY:G: BS 
DESCRIPTION:MW 0001\, Gustav-Niemann-Hörsaal (5510.EG.001)\nGrundlagen: Be
 triebssysteme und Systemsoftware (IN0009) VO\, Standardgruppe\nfix\; Abhal
 tung\;
DTSTAMP:20170111T102303Z
END:VEVENT

**Comment by kordianbruck** [comment] 2017-01-11 21:07
1. DTSTART;TZID=Z:20170111T120000 - is correct. Lecture starts at 13:00
2. DTSTART;TZID=Z:20170112T073000 - is correct. Lecture starts at 08:30
3. DTSTART;TZID=Z:20170116T124500 - is correct. Lecture starts at 13:45

So from my side everything works just fine. Maybe this can help: 
- http://forums.macrumors.com/threads/google-cal-time-in-ical-as-gmt-default-wrong-time-zone.1839975/
- https://support.apple.com/en-us/HT203413

**Comment by pauljohanneskraft** [comment] 2017-01-11 22:01
I investigated a bit, didn't get the calendar to work, but TUMonline handles .ics files a bit different:

There the time zone is set to Europe/Vienna at the beginning and DTSTART/DTEND without TZID=Z

Calendar on macOS recognizes it as floating...

**Comment by kordianbruck** [comment] 2017-01-25 17:12
I can change the Timezone to Europe/Vienna, but some resources advise against it, as some older clients do not support that. I could add a flag, so that this is optional - would that work @pauljohanneskraft ?

**Comment by larslue** [comment] 2017-05-22 08:03
Hi kordian,
I have the same issue when importing the calendar via proxy with my iPhone. The standard calendar app moves the schedule to be two hours earlier. As we have DST at the moment I guess it moves the appointments to UTC.

I tried the fixes as described in the links, specifically switching on Timezone Override, but it doesn't change anything.

Could you try the fix that you pointed out and set the timezone at the beginning of the ical file?

Thanks!

**Comment by Alwinius** [comment] 2017-10-21 16:55
https://icalendar.org/validator.html gives me an error on the output of this service. The original ical from tumonline is ok though.

**Comment by kordianbruck** [comment] 2017-10-21 23:00
@Alwinius thanks for pointing this out. Seems that no everyone supports this or this not in the standard. I've fixed the Timezone component. @pauljohanneskraft @larslue can you confirm its correct now?

For future reference heres the usage from the lib, but its not clear to me if they automatically distinguish between Daylight saving time or not. Maybe have to fix this again, once we switch. 
https://github.com/markuspoerschke/iCal/blob/master/examples/example5.php

**Comment by Alwinius** [comment] 2017-10-22 07:43
Thanks for reacting that fast. However I get a HTTP 500 now.

**Comment by kordianbruck** [comment] 2017-10-22 14:37
@Alwinius sorry, my fault. I didn't account for the updated ical lib

**Comment by Alwinius** [comment] 2017-10-23 15:38
Sorry to bother you again, but I still have trouble importing the ical to outlook.com (necessary to display it in Windows 10 natively). https://icalendar.org/validator.html shows another error about time zones too. outlook.com definitely worked with your feed a couple of days ago.

**Comment by kordianbruck** [comment] 2017-10-23 15:41
Can you post the error From outlook please?

**Comment by Alwinius** [comment] 2017-10-23 15:45
There's no error. It's just that I add the URL in outlook.com (https://outlook.live.com/owa/?path=/calendar/view/Month you can access it with any kind of Microsoft account) and no entries appear at all.

**Comment by Alwinius** [comment] 2017-10-24 15:47
I can confirm that this is working now.

**Comment by kordianbruck** [comment] 2017-10-24 21:03
Cool, then I can close this then. Thanks for fixing it @markuspi

**Closed by kordianbruck** 2017-10-24 21:03 UTC
Labels: question
